-- AlterTable - Add individual border columns
ALTER TABLE "cells" ADD COLUMN IF NOT EXISTS "borderTop" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "cells" ADD COLUMN IF NOT EXISTS "borderBottom" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "cells" ADD COLUMN IF NOT EXISTS "borderLeft" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "cells" ADD COLUMN IF NOT EXISTS "borderRight" BOOLEAN NOT NULL DEFAULT false;
